home = '//div[@id="logo"]'
about = '//header//ul[contains(@class,"top-menu")]/li/a[contains(@href,"o-nas.html")]'
delivery_and_payment = '//header//ul[contains(@class,"top-menu")]/li/a[contains(@href,"dostavka-i-oplata.html")]'
menu = '//div[contains(@class,"mainmenublock")]//div[contains(@class,"mainmenu")]'
tactic_shoes = '//div[contains(@class,"mainmenu")]/ul[@class="list-unstyled"]/li/a[contains(@href,"katalog/obuv")]'
guard_clothes = '//div[contains(@class,"mainmenu")]/ul[@class="list-unstyled"]/li/a[contains(@href,"katalog/forma-ohranyi")]'
fishing_hunting ='//div[contains(@class,"mainmenu")]/ul[@class="list-unstyled"]/li/a[contains(@href,"katalog/ryibalka-i-ohota/")]'