version: 2.1

jobs:
  build:
    docker:
      - image: circleci/python:3.9
        environment:
          CHROME_BIN: /usr/bin/google-chrome

    working_directory: ~/repo

    steps:
      - checkout:
          path: ~/repo
          persist_to_workspace:
            root: ~/repo
          git:
            depth: 1
            submodules: false
            fetch_tags: false
            url: https://github.com/builuk/QALight_killa_frame.git

      # Install Chrome and ChromeDriver
      - run:
          name: Install Chrome and ChromeDriver
          command: |
            sudo apt-get update
            sudo apt-get install -y google-chrome-stable
            LATEST_CHROMEDRIVER_VERSION=$(curl -sS chromedriver.storage.googleapis.com/LATEST_RELEASE)
            curl -o /tmp/chromedriver.zip "https://chromedriver.storage.googleapis.com/$LATEST_CHROMEDRIVER_VERSION/chromedriver_linux64.zip"
            sudo unzip /tmp/chromedriver.zip chromedriver -d /usr/local/bin/
            sudo chmod +x /usr/local/bin/chromedriver

      # Install dependencies
      - run:
          name: Install dependencies
          command: |
            pip install -r requirements.txt

      # Run tests
      - run:
          name: Run tests
          command: |
            behave features/test

workflows:
  version: 2
  build:
    jobs:
      - build
