version: 2.1

jobs:
  build:
    docker:
      - image: circleci/python:3.9

    working_directory: ~/repo

    steps:
      - checkout:
          path: ~/repo
          persist_to_workspace:
            root: ~/repo
          git:
            depth: 1
            submodules: false
            fetch_tags: false
            url: https://github.com/builuk/QALight_killa_frame.git

      # Install dependencies
      - run:
          name: Install dependencies
          command: |
            pip install -r requirements.txt

      # Run tests
      - run:
          name: Run tests
          command: |
            pytest
            behave

workflows:
  version: 2
  build:
    jobs:
      - build
